name: 'Push Changes'
description: 'Commits and pushes changes in l10n and upstream directories'
inputs:
  message:
    description: 'Commit message'
    required: true
runs:
  using: "composite"
  steps:
    - name: Commit
      uses: ./.github/actions/commit-changes
      with:
        message: ${{ inputs.message }}

    - name: Push
      shell: bash
      run: |
        git fetch origin main
        git rebase origin/main
        git push origin main
