name: 'Push Changes'
description: 'Pushes local commits to origin/main'
runs:
  using: "composite"
  steps:
    - name: Push
      shell: bash
      run: |
        git fetch origin main
        git rebase origin/main
        git push origin main
