#!/usr/bin/env bash
set -eu

SCRIPT_DIR=$(cd $(dirname $0); pwd)
L10N_HOME=$(cd $(dirname $(dirname $SCRIPT_DIR)); pwd)
cd $L10N_HOME

set +e
git diff --exit-code --quiet ./l10n/stats/override.csv
UPDATE_CHECK_EXIT_CODE=$?
set -e

set +e
cat ./l10n/stats/override.csv | awk -F "," 'NR>1 {print $4}' | grep NG > /dev/null
NG_CHECK_EXIT_CODE=$?
set -e

echo $UPDATE_CHECK_EXIT_CODE
echo $NG_CHECK_EXIT_CODE

if [ $UPDATE_CHECK_EXIT_CODE -ne 0 -a $NG_CHECK_EXIT_CODE -eq 0 ] ; then
  gh issue create --title "Corresponding files of those in the override directory are updated" --body "Corresponding files of those in the override directory are updated. see [override stats](https://github.com/quarkusio/ja.quarkus.io/blob/main/l10n/stats/override.csv) for more details."
fi
