---
quarkus:
  smallrye-graphql-client:
    github:
      header:
        Authorization: 'Bearer ${GITHUB_TOKEN}'
      url: https://api.github.com/graphql
working-groups:
  organizations:
    - quarkusio
    - quarkiverse
  project-prefix: 'WG -'
