---
services:
  jekyll:
    build: jekyll-container/
    command: [ "bundle", "exec", "jekyll", "serve", "--force_polling", "-H", "0.0.0.0", "-P", "4000", "--incremental", "--config", "_config.yml,_config_dev.yml,_noguides_config.yml" ]
    ports:
      - 4000:4000
    volumes:
      - .:/site:Z
