---
contributors:
  months: 24
  opt-in-url: https://raw.githubusercontent.com/quarkusio/quarkus-extension-catalog/main/named-contributing-orgs-opt-in.yml
  org: quarkusio
  output: contributors.yaml
  repo: quarkus
quarkus:
  smallrye-graphql-client:
    github:
      header:
        Authorization: 'Bearer ${GITHUB_TOKEN}'
      url: https://api.github.com/graphql
