name: build

on:
  push:
    branches:
      - 'main'
  schedule:
    # everyday 9AM (UTC)
    - cron: '0 9 * * *'
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'sync-upstream'
    branches:
      - 'main'
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    name: Update files
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 50
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache bundle directory
        uses: actions/cache@v5
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}

      - name: Cache tsuji.jar
        uses: actions/cache@v5
        with:
          path: vendor/tsuji
          key: ${{ runner.os }}-tsuji-${{ hashFiles('config/application.yaml') }}

      - name: Setup build env
        run: bin/setup-build-env-on-ubuntu

      - name: Update fuzzy tmx
        run: ./tsujiw tmx generate --tmx=l10n/tmx/fuzzy.tmx --mode=FUZZY

      - name: Push changes (fuzzy tmx)
        uses: ./.github/actions/push-changes
        with:
          message: "Update fuzzy tmx"

      - name: Update tmx
        run: ./tsujiw tmx generate --tmx=l10n/tmx/quarkus.tmx --mode=CONFIRMED

      - name: Push changes (tmx)
        uses: ./.github/actions/push-changes
        with:
          message: "Update tmx"

      - name: Update all stats
        run: ./tsujiw jekyll update-stats

      - name: Push changes (translation stats)
        uses: ./.github/actions/push-changes
        with:
          message: "Update translation stats"

      - name: Create issue if override files updated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! git diff --exit-code --quiet l10n/stats/override.csv; then
            if grep -q "NG" l10n/stats/override.csv; then
              gh issue create \
                --title "Corresponding files of those in the override directory are updated" \
                --body "Corresponding files of those in the override directory are updated. see [override stats](https://github.com/doc-l10n-kit/ja.quarkus.io/blob/main/l10n/stats/override.csv) for more details."
            fi
          fi

      - name: Push changes (override stats)
        uses: ./.github/actions/push-changes
        with:
          message: "Update override stats"

  deploy:
    name: Deploy localized site to GitHub pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache bundle directory
        uses: actions/cache@v5
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}

      - name: Cache tsuji.jar
        uses: actions/cache@v5
        with:
          path: vendor/tsuji
          key: ${{ runner.os }}-tsuji-${{ hashFiles('config/application.yaml') }}

      - name: Setup build env
        run: bin/setup-build-env-on-ubuntu

      - name: Load Configuration
        id: config
        run: |
          {
            echo "git_user_name=$(./tsujiw config get tsuji.git.user.name)"
            echo "git_user_email=$(./tsujiw config get tsuji.git.user.email)"
            echo "jekyll_cname=$(./tsujiw config get tsuji.jekyll.cname)"
          } >> $GITHUB_OUTPUT

      - name: Build
        run: ./tsujiw jekyll build --accept-mt=gemini

      - name: Deploy to GitHub Pages
        env:
          GIT_USER_NAME: ${{ steps.config.outputs.git_user_name }}
          GIT_USER_EMAIL: ${{ steps.config.outputs.git_user_email }}
          GITHUB_PAGES_CNAME: ${{ steps.config.outputs.jekyll_cname }}
        run: |
          if [ -n "$GITHUB_PAGES_CNAME" ]; then
            echo "$GITHUB_PAGES_CNAME" > docs/CNAME
          fi
          git add -f docs

          if ! git diff --cached --exit-code --quiet; then
            git checkout -b docs
            git config user.name "$GIT_USER_NAME"
            git config user.email "$GIT_USER_EMAIL"
            git commit -m "Update GitHub Pages"
            git push -f origin docs
          fi
