name: pull-request

on: pull_request_target

jobs:
  deploy:
    name: Deploy localized site preview to surge.sh
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 5000
          fetch-tags: false

      - name: Checkout merged commit to 'merged' dir
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: merged
          submodules: recursive

      - name: Copy l10n dir
        run: |
          rm -rf l10n
          cp -r merged/l10n ./

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache bundle directory
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}

      - name: Cache tsuji.jar
        uses: actions/cache@v4
        with:
          path: vendor/tsuji
          key: ${{ runner.os }}-tsuji-${{ hashFiles('merged/config/application.yaml') }}

      - name: Setup build env
        run: bin/setup-build-env-on-ubuntu

      - name: Restore mtime
        # git restore-mtime is currently broken in the GH Actions images so using our own updated local copy
        # see https://github.com/MestreLion/git-tools/blob/main/git-restore-mtime
        run: |
          cd upstream
          ./tools/git-restore-mtime

      - name: Build for preview
        run: ./tsujiw jekyll build --accept-mt=gemini --additional-configs=_only_latest_guides_config.yml

      - name: Reduce the size of the website to be compatible with surge
        run: |
          cd upstream
          find assets/images/posts/ -mindepth 1 -maxdepth 1 -type d -mtime +50 -exec rm -rf ../docs/{} \;
          find newsletter/ -mindepth 1 -maxdepth 1 -type d -mtime +50 -exec rm -rf ../docs/{} \;
          rm -rf ../docs/assets/stickers
          rm -rf ../docs/assets/images/worldtour/2023
          rm -rf ../docs/assets/images/worldtour/2024
          rm -rf ../docs/assets/images/desktopwallpapers
          rm -rf ../docs/assets/images/stickers

      - name: Load Configuration
        id: config
        run: |
          SURGE_DOMAIN_SUFFIX=$(./tsujiw config get tsuji.jekyll.surge-domain-suffix)
          echo "surge_domain_suffix=${SURGE_DOMAIN_SUFFIX}" >> $GITHUB_OUTPUT

      - name: Deploy to surge
        run: |
          surge docs pr-preview-${{ github.event.pull_request.number }}-${SURGE_DOMAIN_SUFFIX}
        env:
          SURGE_DOMAIN_SUFFIX: ${{ steps.config.outputs.surge_domain_suffix }}
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - name: Add comment
        uses: actions/github-script@v9
        with:
          script: |
            const suffix = "${{ steps.config.outputs.surge_domain_suffix }}";
            let body = `Site preview(ja): https://pr-preview-${context.issue.number}-${suffix}`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
